name: Publish to NPM

on:
  workflow_dispatch:
    branches: [main]
  release:
    types: [created]
  push:
    paths:
      - 'package.json'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Dependency install
        run: yarn
      - name: Compile
        run: yarn build
      - name: Publish 
        run: npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
